### ISSUE TITLE
db cluster parameter group requires property parameters

### ISSUE THREAD

**Issue by Guslington** [theonestack/hl-component-aurora-postgres#2]
At the moment if no properties are defined in config resource tries to create with no parameters.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbclusterparametergroup.html#cfn-rds-dbclusterparametergroup-parameters

the condition probably needs to be on the whole resource to not render or provide some sensible default parameters.

**Comment by aaronwalker** [comment]
@Guslington default could be 

```yaml
cluster_parameters:
  timezone: "UTC"
```

**Comment by Samseppiol** [comment]
Fixed in: https://github.com/theonestack/hl-component-aurora-postgres/pull/4
